### ISSUE TITLE
Adding a new connection sometimes results in an empty tag

### ISSUE THREAD

**Issue by simoliva-sunny** [IMNOTIKE/seraphim-cli#7]
Adding a new connection through the `seraphim db ac` command sometimes results in:
```yaml
- ""
  host: <correct host>
  user: <correct user>
  password: <correct password>
  provider: <correct provider>
  default_database: <correct def db>
```
Resulting in an empty entry in the list of connections when performing `seraphim db dmp`
